version: "3.9"

services:
  seed:
    build: ./backend
    command: >
      sh -c "python /app/data/seed.py &&
           python /app/data/train_models.py"


    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./backend:/app

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      seed:
        condition: service_completed_successfully

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
